In [1]:
import torch
import torch.nn as nn

class ClassDropout(nn.Module):
    def __init__(self, num_classes, p=0.5):
        super(ClassDropout, self).__init__()
        self.num_classes = num_classes
        self.p = p

    def forward(self, input, labels):
        if self.training:
            batch_size, num_features = input.size()
            dropout_mask = torch.ones_like(input)

            for i in range(self.num_classes):
                class_size = num_features // self.num_classes
                start = i * class_size
                end = (i + 1) * class_size

                # Generate dropout mask for each class
                mask = torch.zeros((batch_size, class_size))
                mask[labels == i, :class_size//10] = 1

                dropout_mask[:, start:end] *= mask

            output = input * dropout_mask
        else:
            output = input

        return output

In [25]:
# Example usage
dropout = ClassDropout(num_classes=2, p=0.5)
x = torch.randn(10, 4)
labels = torch.randint(0, 4, (10,))
output = dropout(x, labels)

In [26]:
output

tensor([[0., -0., 0., 0.],
        [0., 0., -0., 0.],
        [0., 0., 0., 0.],
        [-0., 0., 0., -0.],
        [0., -0., 0., -0.],
        [-0., 0., 0., -0.],
        [-0., 0., 0., -0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [-0., -0., 0., 0.]])

In [22]:
labels

tensor([2, 1, 2, 0, 0, 2, 1, 1, 0, 0])

In [32]:
import torch
import torch.nn as nn

class LabelDropout(nn.Module):
    def __init__(self, p=0.5):
        super(LabelDropout, self).__init__()
        self.p = p

    def forward(self, input, labels):
        if self.training:
            dropout_mask = torch.ones_like(input, dtype=torch.float32)  # Convert dropout_mask to float32

            # Generate dropout mask based on label
            mask = torch.zeros_like(labels, dtype=torch.float32)  # Convert mask to float32
            mask[labels == 1] = torch.bernoulli(torch.ones_like(labels[labels == 1]).float() * self.p)

            dropout_mask *= mask.unsqueeze(1)

            output = input * dropout_mask
        else:
            output = input

        return output


In [58]:
# Example usage
dropout = LabelDropout(p=0.5)
x = torch.randn(10, 2)
labels = torch.randint(0, 2, (10,))
output = dropout(x, labels)

In [59]:
output

tensor([[ 0.0000, -0.0000],
        [-0.0000,  0.0000],
        [ 0.0000, -0.0000],
        [ 0.0000,  0.0000],
        [-0.0000, -0.0000],
        [ 1.0261,  0.9428],
        [ 0.0000,  0.0000],
        [-0.6378, -0.9000],
        [ 1.2907, -0.1097],
        [-0.0000,  0.0000]])

In [60]:
labels

tensor([0, 0, 0, 0, 0, 1, 0, 1, 1, 0])

In [76]:
import torch
import torch.nn as nn

dropout = nn.Dropout(p=0.5)

# Example usage
output = dropout(x)
output

tensor([[ 1.1459, -0.0000],
        [ 4.7492, -0.0000],
        [-0.0000,  0.9335],
        [ 0.0000, -0.0000],
        [-0.0000, -0.1842],
        [-0.0000,  0.0000],
        [-0.0000, -0.0672],
        [ 0.8640, -2.0705],
        [ 0.0000, -2.4501],
        [-5.7576, -0.0000]])

In [77]:
import torch
import torch.nn as nn

class LabelDropout(nn.Module):
    def __init__(self, p=0.5):
        super(LabelDropout, self).__init__()
        self.p = p
        self.item = 0

    def forward(self, input, labels):
        if self.training:
            if self.item == len(labels) -1:
                self.item = 0 # end of forward
            self.item += 1
            dropout_mask = torch.ones_like(input, dtype=torch.float32)  # Convert dropout_mask to float32

            # Generate dropout mask based on label
            mask = torch.zeros_like(dropout_mask, dtype=torch.float32)  # Convert mask to float32

            # Turn off the 0th neuron for label 0
            mask[labels == 0, 0] = 1.0 - self.p

            # Turn off the 1st neuron for label 1
            mask[labels == 1, 1] = 1.0 - self.p

            dropout_mask *= mask

            output = input * dropout_mask
        else:
            output = input

        return output




In [78]:
x = torch.randn(10, 2)


In [79]:
# Example usage
dropout = LabelDropout(p=0.5)
labels = torch.randint(0, 2, (10,))
output = dropout(x, labels)
output

tensor([[ 0.0000, -0.3690],
        [ 0.0000, -0.2702],
        [ 0.0000, -1.0179],
        [ 0.0000,  0.2240],
        [-0.0000,  0.2196],
        [-0.7385,  0.0000],
        [ 0.0334,  0.0000],
        [ 0.0000,  0.2228],
        [ 0.0000, -0.5198],
        [-0.3733, -0.0000]])

In [80]:
labels

tensor([1, 1, 1, 1, 1, 0, 0, 1, 1, 0])

In [81]:
dropout.item

1

In [156]:
import torch
import torch.nn as nn

import torch
import torch.nn as nn

class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.conv = nn.Conv2d(1, 16, kernel_size=3, stride=1, padding=1)
        self.maxpool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.linear = nn.Linear(16 * 14 * 14, 10)

    def forward(self, input, labels):
        print(labels)
        batch_size = input.size(0)
        print(batch_size)
        output = self.conv(input)
        print(output.shape)
        output = self.maxpool(output)
        print(output.shape)
        output = output.view(batch_size, -1)  # Reshape output to [batch_size, num_features]
        print(output.shape)
        output = self.linear(output)
        print(output.shape)
        return output

# Create an instance of the module
module = MyModule()



In [3]:
# Generate a batch of input tensors
input_batch = torch.randn(64, 1, 28, 28)  # Batch size of 64, input with 1 channel, 28x28 size

In [158]:
# Pass the input batch through the module
labels = torch.randint(low=0, high=10, size=(64,))

output_batch = module(input_batch, labels)
print(output_batch)
output_batch.shape

tensor([6, 0, 1, 9, 4, 5, 3, 1, 2, 6, 6, 3, 5, 4, 7, 7, 8, 5, 2, 3, 8, 4, 3, 2,
        4, 2, 2, 0, 2, 0, 2, 1, 4, 7, 8, 2, 8, 1, 4, 5, 2, 8, 3, 5, 9, 1, 1, 2,
        3, 0, 4, 1, 6, 6, 7, 6, 6, 4, 4, 9, 0, 1, 1, 8])
64
torch.Size([64, 16, 28, 28])
torch.Size([64, 16, 14, 14])
torch.Size([64, 3136])
torch.Size([64, 10])
tensor([[ 0.1822,  0.0377, -0.2974,  0.0109, -0.8199,  0.2558, -0.4759, -0.3422,
         -0.2189,  0.1247],
        [ 0.5903,  0.5092,  0.1869, -0.3818, -0.0939,  0.0187, -0.4818,  0.0236,
         -0.5225,  0.0729],
        [ 0.1212,  0.7494, -0.2593, -0.1949, -0.8086, -0.1106, -0.3424, -0.1479,
         -0.1246, -0.5434],
        [ 0.2075,  0.4368,  0.2989, -0.8117, -0.6151,  0.2387, -0.7075, -0.3671,
         -0.4976, -0.0128],
        [ 0.1929, -0.0650, -0.1420, -0.3704, -0.5443,  0.3669, -0.8789, -0.3265,
         -1.0529,  0.3100],
        [ 0.5688,  0.0724, -0.1103, -0.4128, -0.6750,  0.2666, -0.6940, -0.1717,
         -0.7910,  0.2909],
        [ 0.0706,  0.323

torch.Size([64, 10])

In [154]:
import torch
import torch.nn as nn

class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.linear = nn.Linear(10, 5)

    def forward(self, input, arg1, arg2):
        print(arg2)
        # Use arg1 and arg2 in the forward computation
        output = self.linear(input)
        return output

# Create an instance of the module
module = MyModule()

# Generate a batch of input tensors
input_batch = torch.randn(64, 10)  # Batch size of 64

# Pass the input batch and additional arguments through the module
arg1 = 1
arg2 = 'hello'
output_batch = module(input_batch, arg1, arg2)

print(output_batch)


hello
tensor([[-6.4237e-01, -2.4918e-01, -4.6867e-01,  8.4640e-01,  3.3323e-01],
        [-7.6395e-01, -4.7019e-01, -1.6407e-01,  1.5515e+00,  5.0242e-01],
        [-8.3392e-02, -4.2231e-03, -5.0815e-02,  8.0905e-02, -9.5689e-01],
        [ 4.4424e-01,  6.3291e-01,  6.5886e-01, -7.0136e-01, -8.7413e-01],
        [-2.7180e-01, -6.2154e-01,  8.1393e-02,  2.7866e-01, -3.5610e-01],
        [ 2.2319e-01, -1.4222e-02, -9.3739e-02, -3.0192e-01, -1.1041e+00],
        [-1.7145e-01,  5.0058e-01, -7.9980e-02, -3.4856e-01, -7.1968e-01],
        [-2.8983e-01, -4.5293e-01, -3.6488e-01,  7.1441e-01, -1.7725e-01],
        [ 7.6591e-01,  7.4476e-01,  9.1621e-01, -1.2377e+00, -8.4511e-01],
        [ 6.5633e-01, -2.4939e-01, -2.9857e-01,  9.7941e-02, -8.9881e-01],
        [-2.6623e-01,  1.3860e-01,  1.7732e-01,  4.4850e-01, -7.5409e-02],
        [ 6.3799e-01,  3.7170e-01, -3.3426e-01,  1.1796e+00, -5.8039e-01],
        [ 6.5858e-01,  2.4646e-01,  1.0536e+00,  5.8700e-01, -1.6025e-01],
        [ 8.4177e-0

In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class MyModule(nn.Module):
    def __init__(self, p=0.5):
        super(MyModule, self).__init__()
        self.linear = nn.Linear(10, 6)
        self.p = p

    def forward(self, input, labels):
        output = self.linear(input)

        # Compute loss using the predictions and true labels
        loss = F.cross_entropy(output, labels)

        # Apply custom dropout operation based on the labels
        for i in range(len(labels)):
            label = labels[i]
            # Todo: need to pass the right number of labels
            output[i] = custom_dropout(output[i], self.p, label=label, num_of_labels=2)
            # Add more conditions for other labels if needed

        return output, loss

def custom_dropout(tensor, p, label, num_of_labels):
    if p > 0 and tensor.dim() > 0:
        mask = torch.bernoulli(torch.ones_like(tensor) * (1 - p))
        num_elements = mask.numel()
        portion_size = int(num_elements // num_of_labels)
        mask[label*portion_size:(label+1)*portion_size] = 1.0
        return tensor * mask
    return tensor

# Create an instance of the module
module = MyModule(p=1)

# Generate a batch of input tensors and labels
input_batch = torch.randn(6, 10)  # Batch size of 64
labels = torch.randint(0, 2, (6,))  # Random labels

# Pass the input batch and labels through the module
output_batch, loss = module(input_batch, labels)

print(loss)
print(output_batch)
print(labels)


3
3
3
3
3
3
tensor(1.9145, grad_fn=<NllLossBackward0>)
tensor([[-0.0000, 0.0000, -0.0000, 0.5852, 0.1209, 0.4885],
        [-0.0000, -0.0000, -0.0000, 1.0173, 0.0433, 0.5012],
        [0.7642, 0.7154, 0.2257, -0.0000, 0.0000, 0.0000],
        [0.1500, 0.2710, 0.2988, -0.0000, -0.0000, 0.0000],
        [0.5449, 0.1743, 0.1416, -0.0000, 0.0000, -0.0000],
        [0.0000, -0.0000, 0.0000, 0.7141, 0.2616, 1.0926]],
       grad_fn=<CopySlices>)
tensor([1, 1, 0, 0, 0, 1])


In [1]:
import torch
import torch.nn as nn

class CustomDropout(nn.Module):
    """
    :parameter
    p: probability to drop. Bigger p -> Drop more
    """
    def __init__(self, num_of_labels, p=0.5):
        super(CustomDropout, self).__init__()
        self.p = p
        self.num_of_labels = num_of_labels

    def forward(self, batch_input, batch_labels):
        if self.training:
            layer_size = batch_input.size(1)
            batch_size = batch_input.size(0)
            portion_size = int(layer_size // self.num_of_labels)
            print(f"portion_size: {portion_size}")
            print(batch_input)

            for i in range(batch_size):
                label = batch_labels[i].item()
                # print(f"{label} * {portion_size} = {label * portion_size}")
                # print(f"{label+1} * {portion_size} = {(label + 1) * portion_size}")
                mask = torch.bernoulli(torch.ones_like(batch_input[i]) * (1 - self.p))
                # mask = torch.zeros_like()
                # print(label * portion_size, "-", (label + 1) * portion_size)
                print((1.0 + (1/portion_size)))
                mask[label * portion_size : (label + 1) * portion_size] = self.num_of_labels  # give each neuron power of the dropped neurons
                batch_input[i] = batch_input[i] * mask

            output = batch_input
        else:
            output = batch_input

        return output

In [2]:
class MyModule(nn.Module):
    """
    big p -> drop more
    """
    def __init__(self, p=0.5):
        super(MyModule, self).__init__()
        self.linear = nn.Linear(10, 3)
        self.dropout = CustomDropout(3, p)

    def forward(self, input, labels):
        output = self.linear(input)
        # Apply custom dropout operation based on the labels
        output = self.dropout(output, labels)

        return output

In [3]:
# Create an instance of the module
module = MyModule(p=1)

# Generate a batch of input tensors and labels
input_batch = torch.randn(6, 10)  # Batch size of 6

labels = torch.randint(0, 3, (6,))  # Random labels

# Pass the input batch and labels through the module
output_batch = module(input_batch, labels)


output_batch, labels

portion_size: 1
tensor([[ 0.5711, -0.5323,  0.1424],
        [ 0.1427, -0.2607, -0.0401],
        [ 0.8352, -0.4630, -1.0318],
        [-0.0449,  0.1558,  0.4080],
        [ 0.3593, -0.5124, -0.2071],
        [-0.6994, -0.0364,  0.4330]], grad_fn=<AddmmBackward0>)
2.0
2.0
2.0
2.0
2.0
2.0


(tensor([[ 0.0000, -0.0000,  0.4272],
         [ 0.0000, -0.7821, -0.0000],
         [ 0.0000, -1.3891, -0.0000],
         [-0.0000,  0.0000,  1.2241],
         [ 0.0000, -0.0000, -0.6214],
         [-0.0000, -0.0000,  1.2991]], grad_fn=<CopySlices>),
 tensor([2, 1, 1, 2, 2, 2]))

In [124]:
-1.2200/3

-0.4066666666666667

## Todo:
* need to add power in relation to p. now p is 1 so add power of ALL other neurons